config/routes.rb
Rails.application.routes.draw do

  resources :test_mongos
  resources :comments

  resources :sessions

  get 'attachments/show_by_user'
  resources :attachments

  get 'contents/reply'
  post 'contents/forward'
  resources :contents

  get 'users/login'
  post 'users/login'
  get 'users/logout'
  get 'users/followers'
  post 'users/follow'
  resources :users

  get 'mains/welcome'
  get 'mains/index'

  root 'mains#welcome'

end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController

  def index
  end

  def create
    @content = Content.new(content_params)

    if attach_params.blank?
      puts 'attach is blank'
    else
      @packet = Attachpacket.create(user_id: @content.user_id, visible: 1, packet_desc: "")
      @attach = Attachment.new(attach_params)
      @attach.attach_packet_id = @packet.id
      @content.attach_packet_id = @packet.id # judge
      @attach.save
    end

    if @content.save
      redirect_to mains_index_path, flash: {u_id: @content.user_id}
    else
    end
  end

  def reply

  end

  def forward
    print("forward_params: " + forward_params.to_json);
    @forward_content = Content.new(forward_params)
    if @forward_content.save
      redirect_to mains_index_path
    else
    end
  end

  def destroy
  end

  private
  def content_params
    params.require(:content).permit(:text, :user_id)
  end

  def attach_params
    params.require(:content).permit(:attach)
  end

  def forward_params
    params.require(:forward).permit(:text, :source_id, :user_id)
  end

end

app/views/contents/_content_forward.html.erb
<%= form_for :forward, :html=> {:class => 'form-horizontal', :role => 'form'}, url: contents_forward_path do |f| %>
  <%= f.hidden_field :source_id, :value => content.id %>
  <%= f.hidden_field :user_id, :value => @user.id %>
  
  <!-- forward.hidden_field format chaos -->
  <div class="col-sm-12">
    <div class="input-group">
      <%= f.text_field :text, class: "form-control", placeholder: "Add a forward..." %>
      <span class="input-group-btn">
        <button class="btn btn-default">
          <i class="glyphicon glyphicon-share"></i>
        </button>        
      </span>
    </div>
  </div>
<% end %>

app/views/contents/_content_post.html.erb
<%= form_for :content, url: contents_path do |f| %>
<%= f.hidden_field :user_id, :value => @user.id %>

<div class="form-group">
  <%= f.text_area :text, class: "form-control" %>
</div>
<%= f.submit "Post", class: "btn btn-success pull-right" %>
<ul class="list-inline">
  <li>
    <a href="#">
      <i class="glyphicon glyphicon-align-left">
      </i>
    </a>
  </li>
  <li>
    <a href="#">
      <i class="glyphicon glyphicon-align-center">
      </i>
    </a>
  </li>
  <li>
    <a href="#">
      <i class="glyphicon glyphicon-align-right">
      </i>
    </a>
  </li>
  <li>
    <%= f.file_field :attach %>
  </li>
</ul>
<% end %>

app/views/contents/_content_post_sf.html.erb
<%= simple_form_for :content, url: contents_path do |f| %>

  <%= f.hidden_field :user_id, :value => @user.id %>
  
  <%= f.input :text, label: "Please enter content",  as: :text %>
  <%= f.button :submit, class: "btn btn-success pull-right" %>

<% end %>

app/views/contents/_content_timeline.html.erb
<% @statuses.each do |s| %>
  <div class="col-md-4 col-sm-4" >
    <div class="panel panel-default">
      <div class="panel-heading">
      </div>
      <div class="panel-body">
        <% @content_user = User.find_by_id(s.user_id) %>
        <% if @content_user.nil? %>
        <% else %>
          <div >
            <div class="col-sm-3">
              <%= image_tag @content_user.portrait_uri.url, size: "56x52", class: "image-circle" %>
              <div class="text-center">
                <%= render "users/user_relation" %>
              </div>
            </div>
            <div class="col-sm-9">
              <div class="text-left">
                <strong><%= @content_user.username %></strong>
                <span class="caret"></span>
              </div>
              <div class="clearfix">
              </div>
              <div class="wrap-lengthen">
                <%= s.text %>
                <% @content_attach = Attachment.where(:attach_packet_id => s.attach_packet_id) %>
                <% if @content_attach.blank? %>
                <% else %>
                  <% @content_attach.each do |atth| %>
                    <%= image_tag atth.attach.url, size: "200x180" %>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <div class="well">
        <div class="row">
          <%= render :partial => "contents/content_forward", :locals => {:content => s} %>
          <!-- partial default :object, contents because mains render, locals need patrial  -->
        </div>
        <div class="row">
          <%# @content = s #%>
          <%= render :partial => "comments/content_comment", :locals => {:user => @user, :content => s} %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/contents/_followed_contents.html.erb
<% @statuses.each do |s| %>
  <div class="col-md-4 col-sm-4" >
    <div class="panel panel-default">
      <div class="panel-heading">
      </div>
      <div class="panel-body">
        <% @content_user = User.find_by_id(s.user_id) %>
        <% if @content_user.nil? %>
        <% else %>
          <a class="thumbnail pull-left" href="#">
            <%= image_tag @content_user.portrait_uri.url, size: "40x40" %>
          </a>
          <%= @content_user.username %>
          <%= form_for :user_relations, method: :post, url: users_follow_path do |ur| %>
            <%= ur.hidden_field  :id, :value => @content_user.id %>
            <% @user_relation = UserRelation.where(:user_id => @user.id, :firend_id => @content_user.id).first %>
            <% if @user_relation.nil? || @user_relation.relation == UserRelation::NORMAL || @user_relation.relation == UserRelation::FOLLOWED %>
              <%= ur.submit "follow", class: "btn" %>
            <% elsif @user_relation.relation == UserRelation::FIREND %>
              <%= ur.submit "firend", class: "btn" %>
            <% else %>
              <%= ur.submit "followed", class: "btn" %>
            <% end %>
          <% end %>
          <div class="clearfix">
          </div>
          <hr />
          <div class="wrap-lengthen">
            <%= s.text %>
            <% @content_attach = Attachment.where(:attach_packet_id => s.attach_packet_id) %>
            <% if @content_attach.blank? %>
            <% else %>
              <% @content_attach.each do |atth| %>
                <%= image_tag atth.attach.url, size: "260x220" %>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="well">
        <div class="forward">
          <%= form_for :forward, :html=> {:class => 'form-horizontal', :role => 'form'}, url: contents_forward_path do |forward| %>
            <%= forward.hidden_field :source_id, :value => s.id %>
            <div class="form-group">
              <div class="col-sm-10">
                <%= forward.text_field :text, class: "form-control", placeholder: "Add a forward..." %>
              </div>
              <button class="btn btn-default col-sm-2">
                <i class="glyphicon glyphicon-share"></i>
              </button>
           </div>
        <% end %>
      </div>
      <div class="comment">
        <%= form_for :comment, :html => {:class => 'form-horizontal', :role => 'form'}, url: comments_path do |c| %>
          <!--form accept-charset="utf-8" action="/comments" enctype="multipart/form-data" method="post" /-->
          <%= c.hidden_field :user_id, :value =>  @user.id %>
          <%= c.hidden_field :content_id, :value => s.id %>
          <div class="form-group">
            <div class="col-sm-10">
              <%= c.text_field :text, class: "form-control", placeholder: "Add a comment..."  %>
            </div>
            <button class="btn btn-default col-sm-2">
              <i class="glyphicon glyphicon-comment"></i>
            </button>
          </div>
        <% end %>
      </div>
      </div>
    </div>
  </div>
<% end %>

app/views/contents/_post_content.html.erb
<%= form_for :content, url: contents_path do |f| %>
<%= f.hidden_field :user_id, :value => @user.id %>

<div class="form-group">
  <%= f.text_area :text, class: "form-control" %>
</div>
<%= f.submit "Post", class: "btn btn-success pull-right" %>
<ul class="list-inline">
  <li>
    <a href="#">
      <i class="glyphicon glyphicon-align-left">
      </i>
    </a>
  </li>
  <li>
    <a href="#">
      <i class="glyphicon glyphicon-align-center">
      </i>
    </a>
  </li>
  <li>
    <a href="#">
      <i class="glyphicon glyphicon-align-right">
      </i>
    </a>
  </li>
  <li>
    <%= f.file_field :attach %>
  </li>
</ul>
<% end %>