config/routes.rb
Rails.application.routes.draw do

  resources :test_mongos
  resources :comments

  resources :sessions

  get 'attachments/show_by_user'
  resources :attachments

  get 'contents/reply'
  post 'contents/forward'
  resources :contents

  get 'users/login'
  post 'users/login'
  get 'users/logout'
  get 'users/followers'
  post 'users/follow'
  resources :users

  get 'mains/welcome'
  get 'mains/index'

  root 'mains#welcome'

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def profile
  end

  def modify
  end

  def create
    @user = User.create(user_params)  # new to create
    if @user.save
      redirect_to '/'
    else
      render template: 'user/_register' # redirect_to no transfer
    end
  end

  def login
    unless request.get?
      username = params[:user][:username]
      password = params[:user][:password]
      @hint = "ok"
      @user = User.find_by_username(username)
      if @user.class == NilClass
        @hint = 'unregisted username!'
        redirect_to main_welcome_path
      elsif @user.password == password
        @hint = 'welcome back'
        puts "login user id #{@user.id}"
        redirect_to main_index_path, status: 301, flash: {u_id: @user.id}
      else
        @hint = 'login failed, please check up you info'
      end
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password, :portrait_uri)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.create(params_new_user)  # new to create
    if @user.save
      redirect_to '/', notice: "User was successfully created." # redirect_to no transfer
    else
      # render partial: 'user_register_sf', layout: 'sf_label', locals: {title: 'Register error'} # partial not need _xxx
      render 'mains/welcome'
    end
  end

  def follow
    @user_id = session[:user_id]
    @firend = User.new(firend_params)
    @firend_id = @firend.id
    @user_relation = UserRelation.where(:user_id => @user_id, :firend_id => @firend_id).first
    if @user_relation.nil?
      @user_relation = UserRelation.new(:user_id => @user_id, :firend_id => @firend_id)
      @user_relation.relation = UserRelation::FOLLOW
      @user_relation.follow_time = Time.new
    else
      if @user_relation.relation == UserRelation::FOLLOW
        @user_relation.relation = UserRelation::NORMAL
        @user_relation.follow_time = NIL
      elsif @user_relation.relation == UserRelation::FIREND
        @user_relation.relation = UserRelation::FOLLOWED
        @user_relation.follow_time = Time.new
        @user_relation.follow_time = NIL
      elsif @user_relation.relation == UserRelation::FOLLOWED
        @user_relation.relation = UserRelation::FIREND
      else
        @user_relation.relation = UserRelation::FOLLOW
        @user_relation.follow_time = Time.new
      end
    end
    
    @firend_relation = UserRelation.where(:user_id => @firend_id, :firend_id => @user_id).first
    if @firend_relation.nil?
      @firend_relation = UserRelation.new(:user_id => @firend_id, :firend_id => @user_id)
      @firend_relation.relation = UserRelation::FOLLOWED
      @firend_relation.followed_time = Time.new
    else
      if @firend_relation.relation == UserRelation::FOLLOW
        @firend_relation.relation = UserRelation::FIREND
        @firend_relation.followed_time = Time.new
      elsif @firend_relation.relation == UserRelation::FOLLOWED
        @firend_relation.relation = UserRelation::NORMAL
        @firend_relation.followed_time = NIL
      elsif @firend_relation.relation == UserRelation::FIREND
        @firend_relation.relation = UserRelation::FOLLOW
        @firend_relation.followed_time = NIL
      else
        @firend_relation.relation = UserRelation::FOLLOWED
        @firend_relation.followed_time = Time.new
      end
    end
    
    if @user_relation.save && @firend_relation.save
      redirect_to mains_index_path
    end
    
  end

  def followers
    @user_relation = UserRelation.where(:firend_id => session[:user_id])
    if @user_relation.nil?
      
    else
      @user_relation.each do |ur|
        
      end
    end

  end

  def login
    unless request.get?
      username = params[:user][:username]
      password = params[:user][:password]
      @hint = "ok"
      @user = User.find_by_username(username)
      if @user.class == NilClass
        @hint = 'unregisted username!'
        redirect_to mains_welcome_path
      elsif User.authen_by_username(username, password)
        @hint = 'welcome back'
        puts "login user id #{@user.id}"
        session[:user_name] = username
        session[:user_id] = @user.id
        redirect_to mains_index_path, status: 301, flash: {u_id: @user.id}
      else
        @hint = 'login failed, please check up you info'
      end
    end
  end

  def logout
    reset_session
    redirect_to mains_welcome_path
  end
  
  private
  def params_new_user
    params.require(:user).permit(:username, :email, :form_password, :password_confirm);
  end
  # def user_params
  #   params.require(:user).permit(:username, :email, :form_password, :portrait_uri)
  # end
  def firend_params
    params.require(:user_relations).permit(:id)
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_horizontal_login_sf.html.erb
<%= simple_form_for :session, url: sessions_path, html: {class: 'form-horizontal'},
  wrapper: :horizontal_form, wrapper_mappings: {
  } do |f| %>

<%= f.error_notification %>

<%= f.input :username, placeholder: 'Username' %>
<%= f.input :password, placeholder: 'Password' %>
<%= f.button :submit, "Confirm" %>

<% end %>

app/views/users/_register.html.erb
<%= form_for :user, :html => {:id => 'signupform', :class => 'form-horizontal', :role => 'form'}, url: users_path do |f| %>

  <div class="container-fluid">
    <div class="register_portrait">
      <%#= f.file_field :portrait_uri, class: "portrait_browser" #%>
    </div>
    <div class="register_info">
      <% if @user.errors.any? %>

        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved.</h2>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
              <li> <%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :username, class: "col-sm-4 control-label" %>
        <div class="col-lg-7">
          <%= f.text_field :username, class: "form-control required" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :email, class: "col-sm-4 control-label" %>
        <div class="col-lg-7">
          <%= f.text_field :email, class: "form-control required email" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :password, class: "col-sm-4 control-label" %>
        <div class="col-lg-7">
          <%= f.password_field :form_password, class: "form-control required" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label "Confirm Password", class: "col-sm-4 control-label" %>
        <div class="col-lg-7">
          <%= f.password_field :password_confirm, class: "form-control required" %>
        </div>
        <div class="col-sm-2 status"> </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-3 col-sm-10">
          <%= f.submit "Sign Up", class: "btn btn-default" %>
          <%= link_to "Sign in",  users_login_path, :class => 'btn btn-default' %>
        </div>

      </div>
    </div>
  </div>

<% end %>

app/views/users/_user_login_sf.html.erb
<%= simple_form_for :session, url: sessions_path, html: {id: 'userform', class: 'form-horizontal'},
  wrapper: :horizontal_form, wrapper_mappings: {
  } do |f| %>

<%= f.error_notification %>

<%= f.input :username, placeholder: 'Username' %>
<%= f.input :password, placeholder: 'Password' %>
<%= f.button :submit, "Confirm" %>

<% end %>

app/views/users/_user_login_tb.html.erb
<%= form_for :session, :html => {:class => 'form-horizontal', :role => 'form'}, :url => sessions_path do |f| %>
  <div class="form-group">
    <%= f.label :username, class: "col-sm-3 control-label col-md-offset-0" %>
    <div class="col-sm-9">
      <%= f.text_field :username, class: "form-control required" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password, class: "col-sm-3 control-label col-md-offset-0" %>
    <div class="col-sm-9">
      <%= f.password_field :password, class: "form-control required" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10 col-md-offset-1" >
      <%= f.submit "Confirm", class: "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/users/_user_profile.html.erb
<div class="media">
  <a class="thumbnail pull-left" href="#">
    <%= image_tag @user.portrait_uri.url, size: "80x80" %>
  </a>
  <div class="media-body">
    <h4 class="media-heading">
      <%= @user.username %>
    </h4>
    <p>
      <% @packets = Attachpacket.where(user_id: "#{@user.id}").select("id") %>
      <% if @packets.nil? %>
        <span class="label label-primary">0 photos</span>
      <% else %>
        <% @attach_count = Attachment.where("attach_packet_id in (?)", @packets.ids).count %>
        <%= link_to "#@attach_count photos", attachments_show_by_user_path(:user_id=> @user.id), class: "label label-primary" %>
      <% end %>

      <% @followers_count = UserRelation.where(firend_id: "#{@user.id}").count %>
      <%= link_to "#@followers_count followers", users_followers_path, class: "label label-primary"  %>
    </p>
    <p>
      <a class="btn btn-xs btn-default" href="#">
        <span class="glyphicon glyphicon-comment">
        </span>Message
      </a>
      <a class="btn btn-xs btn-default" href="#">
        <span class="glyphicon glyphicon-heart">
        </span>Favorite
      </a>
    </p>
  </div>
</div>

app/views/users/_user_register_sf.html.erb
<%= simple_form_for :user, :html => {:id => 'userform' }, url: users_path do |f| %>

  <%= f.error_notification %>
  <%= f.input :username, placeholder: 'Username' %>
  <%= f.input :email, placeholder: 'Email' %>
  <%= f.input :form_password, placeholder: "Password" %>
  <%= f.input :password_confirm, placeholder: "Password Confirm" %>
  <%= f.button :submit, "Sign up" %>
  <%= link_to "Sign in", users_login_path, :class => 'btn btn-default' %>

<% end %>

app/views/users/_user_relation.html.erb
<%= form_for :user_relations, method: :post, url: users_follow_path do |ur| %>
  <%= ur.hidden_field  :id, :value => @content_user.id %>
  <% @user_relation = UserRelation.where(:user_id => @user.id, :firend_id => @content_user.id).first %>
  <% if @user_relation.nil? || @user_relation.relation == UserRelation::NORMAL || @user_relation.relation == UserRelation::FOLLOWED %>
    <%= ur.submit "follow", class: "btn btn-xs btn-primary" %>
  <% elsif @user_relation.relation == UserRelation::FIREND %>
    <%= ur.submit "firend", class: "btn btn-xs active" %>
  <% else %>
    <%= ur.submit "followed", class: "btn btn-xs btn-success text-center" %>
  <% end %>
<% end %>

app/views/users/followers.html.erb
<% if @user_relation.blank?  %>
  <p> no followers </p>
<% else %>
  <% @user_relation.each do |ur| %>
    <% @user = User.find_by_id(ur.user_id) %>
    <%= render "users/user_profile" %>
  <% end %>
<% end %>

app/views/users/login.html.erb
<div class="row">
  <%= render partial: 'users/user_login_sf', layout: 'layouts/sf_label', locals: {title: 'User Login'} %>
</div>