config/routes.rb
Rails.application.routes.draw do

  resources :test_mongos
  resources :comments

  resources :sessions

  get 'attachments/show_by_user'
  resources :attachments

  get 'contents/reply'
  post 'contents/forward'
  resources :contents

  get 'users/login'
  post 'users/login'
  get 'users/logout'
  get 'users/followers'
  post 'users/follow'
  resources :users

  get 'mains/welcome'
  get 'mains/index'

  root 'mains#welcome'

end

app/controllers/test_mongos_controller.rb
class TestMongosController < ApplicationController
  before_action :set_test_mongo, only: [:show, :edit, :update, :destroy]

  # GET /test_mongos
  # GET /test_mongos.json
  def index
    @test_mongos = TestMongo.all
  end

  # GET /test_mongos/1
  # GET /test_mongos/1.json
  def show
  end

  # GET /test_mongos/new
  def new
    @test_mongo = TestMongo.new
  end

  # GET /test_mongos/1/edit
  def edit
  end

  # POST /test_mongos
  # POST /test_mongos.json
  def create
    @test_mongo = TestMongo.new(test_mongo_params)

    respond_to do |format|
      if @test_mongo.save
        format.html { redirect_to @test_mongo, notice: 'Test mongo was successfully created.' }
        format.json { render :show, status: :created, location: @test_mongo }
      else
        format.html { render :new }
        format.json { render json: @test_mongo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /test_mongos/1
  # PATCH/PUT /test_mongos/1.json
  def update
    respond_to do |format|
      if @test_mongo.update(test_mongo_params)
        format.html { redirect_to @test_mongo, notice: 'Test mongo was successfully updated.' }
        format.json { render :show, status: :ok, location: @test_mongo }
      else
        format.html { render :edit }
        format.json { render json: @test_mongo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /test_mongos/1
  # DELETE /test_mongos/1.json
  def destroy
    @test_mongo.destroy
    respond_to do |format|
      format.html { redirect_to test_mongos_url, notice: 'Test mongo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test_mongo
      @test_mongo = TestMongo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_mongo_params
      params.require(:test_mongo).permit(:name)
    end
end

app/helpers/test_mongos_helper.rb
module TestMongosHelper
end

app/views/test_mongos/_form.html.erb
<%= simple_form_for(@test_mongo) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/test_mongos/edit.html.erb
<h1>Editing Test Mongo</h1>

<%= render 'form', test_mongo: @test_mongo %>

<%= link_to 'Show', @test_mongo %> |
<%= link_to 'Back', test_mongos_path %>

app/views/test_mongos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Test Mongos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @test_mongos.each do |test_mongo| %>
      <tr>
        <td><%= test_mongo.name %></td>
        <td><%= link_to 'Show', test_mongo %></td>
        <td><%= link_to 'Edit', edit_test_mongo_path(test_mongo) %></td>
        <td><%= link_to 'Destroy', test_mongo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Test Mongo', new_test_mongo_path %>

app/views/test_mongos/new.html.erb
<h1>New Test Mongo</h1>

<%= render 'form', test_mongo: @test_mongo %>

<%= link_to 'Back', test_mongos_path %>

app/views/test_mongos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @test_mongo.name %>
</p>

<%= link_to 'Edit', edit_test_mongo_path(@test_mongo) %> |
<%= link_to 'Back', test_mongos_path %>